=== Lev010608/Software-Engeering-2/XMLAndWeb/XML实验/2018级XML实验/实验一/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 rel. 2 (http://www.altova.com) by  () -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3schools.com" targetNamespace="http://www.w3schools.com" elementFormDefault="qualified">
	<!--学院元素(混合元素)-->
	<xs:element name="school">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="grade" type="gradeType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--****************************************-->
	<!--年级类型(Element Only元素)-->
	<xs:complexType name="gradeType">
		<xs:sequence>
			<xs:element name="gradeId" type="xs:string" fixed="2020级"/>
			<xs:element name="class" type="classType" minOccurs="2" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!--****************************************-->
	<!--班级类型-->
	<xs:complexType name="classType">
		<xs:sequence>
			<xs:element name="classId" type="xs:string"/>
			<xs:element name="student" type="studentType" minOccurs="0" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	<!--****************************************-->
	<!--学生类型(Element Only元素)-->
	<xs:complexType name="studentType">
		<xs:sequence>
			<xs:element name="studentId" type="xs:integer"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="Email">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-zA-Z0-9_-]+@[a-zA-Z0-9_.]+(.[a-zA-Z0-9]+)"/>
						<!--邮箱正则匹配-->
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="phoneNumber" type="xs:integer"/>
			<xs:element name="homeAddress" type="addressType"/>
		</xs:sequence>
	</xs:complexType>
	<!--****************************************-->
	<!--地址类型-->
	<xs:complexType name="addressType">
		<xs:sequence>
			<!--省份(空元素)-->
			<xs:element name="province">
				<xs:complexType>
					<xs:attribute name="provinceName" type="xs:string"/>
				</xs:complexType>
			</xs:element>
			<!--城市(空元素)-->
			<xs:element name="city">
				<xs:complexType>
					<xs:attribute name="cityName" type="xs:string"/>
				</xs:complexType>
			</xs:element>
			<!--详细地址-->
			<xs:element name="exactAddress" type="xs:string"/>
			<!--****************************************-->
			<!--邮编(TEXT Only元素)-->
			<xs:element name="postcode">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="postcodeType">
							<xs:attribute name="codingSystem" type="xs:string" fixed="CN"/>
						</xs:extension>
						<!--我国采用四级六位编码制-->
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!--****************************************-->
	<!--邮编类型-->
	<xs:simpleType name="postcodeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{6}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Lev010608/Software-Engeering-2/XMLAndWeb/XML实验/2018级XML实验/实验一/student.xml
<?xml version="1.1" encoding="UTF-8"?>
<school xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com student.xsd">
北京邮电大学 计算机学院(国家示范性软件学院) 按照“面向国家需求，瞄准学科前沿，汇聚优秀人才，争创国际一流”的发展战略，坚持育人为本、教学与科研并重的发展理念，薪火相承，为把我院建设成为世界一流学院而努力奋斗。
	<grade>
		<gradeId>2020级</gradeId>
		<!--班级1-->
		<class>
			<classId>2020211501</classId>
			<!--学生1.1-->
			<student>
				<studentId>2020522108</studentId>
				<name>Jayce</name>
				<Email>1276953157@qq.com</Email>
				<phoneNumber>10086</phoneNumber>
				<homeAddress>
					<province provinceName="北京市"/>
					<city cityName="北京市"/>
					<exactAddress>海淀区-西土城路10号-北京邮电大学</exactAddress>
					<postcode codingSystem="CN">100876</postcode>
				</homeAddress>
			</student>
			<!--学生1.2-->
			<student>
				<studentId>202099999</studentId>
				<name>C</name>
				<Email>153157@163.com</Email>
				<phoneNumber>10086</phoneNumber>
				<homeAddress>
					<province provinceName="北京市"/>
					<city cityName="北京市"/>
					<exactAddress>海淀区-西土城路10号-北京邮电大学</exactAddress>
					<postcode codingSystem="CN">100876</postcode>
				</homeAddress>
			</student>
			<!--学生1.3-->
			<student>
				<studentId>202066666</studentId>
				<name>C++</name>
				<Email>HelloWorld@bupt.edu.cn</Email>
				<phoneNumber>10086</phoneNumber>
				<homeAddress>
					<province provinceName="山东省"/>
					<city cityName="济南市"/>
					<exactAddress>天桥区-无影山东路-43号</exactAddress>
					<postcode codingSystem="CN">100696</postcode>
				</homeAddress>
			</student>
		</class>
		<!--班级2-->
		<class>
			<classId>2020211502</classId>
			<!--学生2.1-->
			<student>
				<studentId>2020119002</studentId>
				<name>Jayce</name>
				<Email>1276953157@qq.com</Email>
				<phoneNumber>10086</phoneNumber>
				<homeAddress>
					<province provinceName="北京市"/>
					<city cityName="北京市"/>
					<exactAddress>海淀区-西土城路10号-北京邮电大学</exactAddress>
					<postcode codingSystem="CN">100876</postcode>
				</homeAddress>
			</student>
			<!--学生2.2-->
			<student>
				<studentId>2020119003</studentId>
				<name>C</name>
				<Email>153157@163.com</Email>
				<phoneNumber>10086</phoneNumber>
				<homeAddress>
					<province provinceName="北京市"/>
					<city cityName="北京市"/>
					<exactAddress>海淀区-西土城路10号-北京邮电大学</exactAddress>
					<postcode codingSystem="CN">100876</postcode>
				</homeAddress>
			</student>
		</class>
	</grade>
</school>
