=== Lev010608/Software-Engeering-2/XMLAndWeb/XML作业/第二次课后作业/people.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--根标签-->
<!ELEMENT People (Person+)>

<!--第一层标签-->
<!ELEMENT Person (Name,Address,Tel,Fax,Email)*>

<!--第二层标签-->
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Tel (#PCDATA)>
<!ELEMENT Fax (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

=== Lev010608/Software-Engeering-2/XMLAndWeb/XML作业/第二次课后作业/people.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE People SYSTEM "people.dtd">

<People>
	<Person></Person>
	<Person>
		<Name>Jayce</Name>
		<Address>Piltover</Address>
		<Tel>10086</Tel>
		<Fax>None</Fax>
		<Email>10010@gmail.com</Email>
	</Person>
	<Person></Person>
</People>

<!--people.xml文件-->
